[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
auto_detect_remappings = false
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/", "forge-std/=lib/forge-std/src/", "@uniswap/v4-core/=lib/uniswap-v4-core/", "@uniswap/v4-periphery/=lib/uniswap-v4-periphery-lite/", "solmate/=lib/solmate/"]

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 128
depth = 64
fail_on_revert = true
