import {createRequire} from 'node:module';
import assert from 'node:assert/strict';import {readFile,writeFile,mkdtemp} from 'node:fs/promises';import {createHash} from 'node:crypto';import {spawn} from 'node:child_process';import {once} from 'node:events';import {createServer} from 'node:http';import {resolve,join,sep} from 'node:path';import {fileURLToPath,pathToFileURL} from 'node:url';import {build} from 'esbuild';import {chromium} from 'playwright';import {npmRun,packageSdk} from './package-sdk.mjs';import {SDK_MODULES} from './build-sdk.mjs';
const root=fileURLToPath(new URL('../',import.meta.url)),selected=await packageSdk(),directory=resolve(selected.directory),tarball=resolve(selected.tarball);
assert(directory.startsWith(resolve(root,'output')+sep));assert(tarball.startsWith(directory+sep));assert.equal('sha512-'+createHash('sha512').update(await readFile(tarball)).digest('base64'),selected.sha512);assert.equal(selected.published,false);
const manifest=JSON.parse(await readFile(join(directory,'sdk-manifest.json')));assert.equal(manifest.version,2);assert.deepEqual(manifest.dependencies,{viem:'2.57.2'});const packedManifest=JSON.parse(await readFile(join(directory,'package.json')));assert.deepEqual(packedManifest.dependencies,{viem:'2.57.2'});assert.equal(packedManifest.private,true);assert.deepEqual(manifest.publicClients,SDK_MODULES);for(const [file,hash]of Object.entries(manifest.sourceHashes))assert.equal(createHash('sha256').update(await readFile(join(root,file))).digest('hex'),hash,'Stale current SDK source '+file);
assert(!selected.files.some(f=>/zkapi|vendor|runtime\/|private|chat|wallet|operator|output\//i.test(f)));const consumer=await mkdtemp(join(root,'output/sdk-consumer-'));await writeFile(join(consumer,'package.json'),JSON.stringify({name:'noerra-current-sdk-consumer',private:true,type:'module'})+'\n');await npmRun(consumer,['install','--ignore-scripts','--no-audit','--no-fund','--save-exact',tarball]);
const sdk=await import(pathToFileURL(join(consumer,'node_modules/@noerra/sdk/dist/index.js')));for(const name of ['NoerraAgentsClient','NoerraAgentChain','NoerraEcosystem','NoerraFlagshipMarket','NoerraComputePool','NoerraAgentDiem','NoerraDiemMarket','NoerraDualMarket','AccessMarket','exportAgentMemory','importAgentMemory','newRoomRequestId','automaticActivationIntent'])assert.equal(typeof sdk[name],'function',name);for(const name of ['NoerraClient','BrowserVault','ZkApiConfidentialChat','sessionTransport','exportPrivateWallet'])assert.equal(name in sdk,false,name);
assert.equal(sdk.displayUsd(1234567n),'1.234567');assert.throws(()=>new sdk.NoerraAgentsClient({origin:'http://unsafe.test'}));let calls=[];const client=new sdk.NoerraAgentsClient({origin:'https://sdk.invalid',fetcher:async(url,init)=>{calls.push({url,init});return Response.json({publicOrigin:'https://sdk.invalid'});}});await client.config();assert.equal(calls[0].url,'https://sdk.invalid/api/agents/config');assert.equal(calls[0].init.redirect,'error');assert.throws(()=>client.sendRoom('a'.repeat(32),'test','fresh-unstable-id'));assert.equal(calls.length,1);assert.equal(sdk.canonicalActivationJson({b:2,a:1}),' {"a":1,"b":2}'.trim());
const agent={owner:'0x'+'12'.repeat(20),id:'a'.repeat(32),name:'SDK fixture',memory:{facts:['local test fixture']},runs:[],journal:[],drafts:[],config:{name:'SDK fixture'}};const backup=await sdk.exportAgentMemory(agent,'test-only-passphrase-123');const restored=await sdk.importAgentMemory(backup,'test-only-passphrase-123');assert.deepEqual(restored.memory,agent.memory);await assert.rejects(sdk.importAgentMemory(backup,'wrong-test-passphrase'));
const types=`import {NoerraAgentsClient,NoerraAgentChain,NoerraEcosystem,NoerraComputePool,NoerraAgentDiem,AccessMarket,automaticActivationIntent,type AgentMemoryBackup} from '@noerra/sdk';\nimport {NoerraAgentsClient as Client} from '@noerra/sdk/agents';\nimport {NoerraAgentChain as Chain} from '@noerra/sdk/agent-chain';\nconst client:Client=new NoerraAgentsClient({origin:'https://withnoerra.com'});\nconst directory=client.directory();\nconst rooms=client.roomMessages('a'.repeat(32),{limit:10});\nconst constructors=[NoerraAgentChain,NoerraEcosystem,NoerraComputePool,NoerraAgentDiem,AccessMarket,Chain];\nconst activation:typeof automaticActivationIntent=automaticActivationIntent;\nlet backup:AgentMemoryBackup|undefined;\nvoid [directory,rooms,constructors,activation,backup];\n`;
await writeFile(join(consumer,'consumer.ts'),types);const tsc=createRequire(import.meta.url).resolve('typescript/bin/tsc'),proc=spawn(process.execPath,[tsc,'--noEmit','--strict','--module','NodeNext','--moduleResolution','NodeNext','--target','ES2022','--lib','ES2022,DOM','consumer.ts'],{cwd:consumer,windowsHide:true,stdio:['ignore','pipe','pipe']});let typeLog='';for(const s of [proc.stdout,proc.stderr])s.on('data',b=>typeLog+=b);const [code]=await once(proc,'close');assert.equal(code,0,typeLog);
const browserEntry=join(consumer,'browser.mjs');await writeFile(browserEntry,"import * as sdk from '@noerra/sdk'; globalThis.noerraSdk=sdk; globalThis.sdkReady=true;\n");await build({entryPoints:[browserEntry],outfile:join(consumer,'browser.js'),bundle:true,format:'esm',platform:'browser',target:'es2022'});
const server=createServer(async(req,res)=>{if(req.url==='/browser.js'){res.setHeader('content-type','application/javascript');res.end(await readFile(join(consumer,'browser.js')));}else if(req.url==='/api/agents/config'){res.setHeader('content-type','application/json');res.end(JSON.stringify({publicOrigin:'local-fixture'}));}else{res.setHeader('content-type','text/html');res.end('<script type="module" src="/browser.js"></script>');}});server.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>globalThis.sdkReady===true);const result=await page.evaluate(async()=>{const sdk=globalThis.noerraSdk,c=new sdk.NoerraAgentsClient({origin:location.origin}),configuration=await c.config(),agent={owner:'0x'+'12'.repeat(20),id:'a'.repeat(32),name:'Fixture',memory:{facts:['browser-local']},runs:[],journal:[],drafts:[],config:{name:'Fixture'}},record=await sdk.exportAgentMemory(agent,'test-browser-passphrase-123'),restored=await sdk.importAgentMemory(record,'test-browser-passphrase-123');return {config:configuration.publicOrigin,memory:restored.memory.facts,legacy:'NoerraClient' in sdk,hasChain:typeof sdk.NoerraAgentChain,requestId:sdk.newRoomRequestId()};});assert.deepEqual(result.memory,['browser-local']);assert.equal(result.config,'local-fixture');assert.equal(result.legacy,false);assert.equal(result.hasChain,'function');assert.match(result.requestId,/^[a-f0-9]{32}$/);}finally{await browser.close();await new Promise(r=>server.close(r));}
await writeFile(join(root,'output/sdk-verification.json'),JSON.stringify({version:2,tarball,integrityVerified:true,installedNode:true,installedBrowser:true,typescript:true,currentClients:SDK_MODULES,legacyExcluded:true,published:false},null,2)+'\n');console.log('Current-agent SDK tarball, isolated Node/browser consumers and TypeScript declarations verified. Nothing published.');
